from langgraph.graph import StateGraph, START, END
from langchain_mistralai.chat_models import ChatMistralAI
from tavily import TavilyClient
from typing_extensions import TypedDict
from langchain.messages import SystemMessage,HumanMessage,AIMessage
from langchain.tools import tool
from dotenv import load_dotenv
import os
import operator
load_dotenv()

model=ChatMistralAI(
    model="mistral-small-latest",
    api_key=os.getenv("MISTRAL_API_KEY")
)

@tool
def get_latest_information(query:str)->str:
    """use this tool for the latest information  from internet
    
    Args:
        query(str):  The query to search for

    Returns: 
         str: The search result

    """
    client=TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))
    response=client.search(query)
    return str(response)

tools=[get_latest_information]
# tools_dict={tool.name: tool for tool in tools}
model_with_tools=model.bind_tools(tools)

#state ka kaam data ko ek node se dusre node me le jana
class State(TypedDict):
    topic: str
    article: str
    review: AIMessage | str
    search_result: str
    workflow: list[str]

def write_article_node(state: State):
    # print("\n===== WRITER NODE =====")
    review_feedback = ""

    if state["review"]:
        if isinstance(state["review"], AIMessage):
            review_feedback = state["review"].content
        else:
            review_feedback = state["review"]

    prompt = f"""
    Topic:
    {state["topic"]}

    Reviewer Feedback:
    {review_feedback}

    Latest Search Result:
    {state["search_result"]}

    Write or rewrite the article using the reviewer feedback and latest search result (if available).

    Return ONLY the article.

    Do not explain what you changed.
    """

    response = model.invoke([
        SystemMessage(
            content="""
                You are a professional technical writer.

                Your job is to write or revise the article.

                Always follow the user's original requirements.

                If reviewer feedback is provided, apply every valid suggestion.

                If latest search results are provided, use them only when they are relevant.

                Do not ignore reviewer feedback.

                Return ONLY the final article.

                Do not explain your changes.
                """
        ),
        HumanMessage(content=prompt)
    ])

    return {
        "article": response.content,
        "workflow": state["workflow"] + ["Writer Agent"]
    }


def review_article_node(state: State):
    # print("\n===== REVIEWER NODE =====")
    response = model_with_tools.invoke([
        SystemMessage(
            content="""
                    You are a professional editor.

                    Your job is ONLY to review the article.

                    Never rewrite the article.

                    Compare the generated article against the ORIGINAL user request.

                    Check every requirement one by one.

                    If ANY requirement is violated, do NOT approve the article.

                    Instead, explain:

                    - Which requirement was violated.
                    - Why it was violated.
                    - Exactly how to fix it.

                    Use the search tool ONLY if verifying the article requires the latest factual information.

                    Do NOT use the search tool for grammar, formatting, length, writing quality, or user-preference checks.

                    Approve the article ONLY when every requirement has been satisfied.

                    If the article is correct, reply EXACTLY:

                    The article is good and does not need any changes.
                    """
        ),
        HumanMessage(
            content=f"""
        Original User Request:
        {state["topic"]}

        Generated Article:
        {state["article"]}
        """
        )
    ])
    return {
        "review": response,
        "workflow": state["workflow"] + ["Reviewer Agent"]
    }



def internet_search_node(state: State):
    # print("\n===== SEARCH NODE =====")
    """
    Search the Internet based on the reviewer's tool call.
    """
    # Get the tool call generated by the reviewer
    tool_call = state["review"].tool_calls[0]
    # Extract the search query
    query = tool_call["args"]["query"]
    # Perform the search
    search_result = get_latest_information.invoke(query)
    # Save the search result in the state
    return {
        "search_result": search_result,
        "workflow": state["workflow"] + ["Internet Search"]
    }


def decide_internet_search(state: State):

    review = state["review"]

    # print("\n===== DECISION NODE =====")
    # print(review.content)

    if isinstance(review, AIMessage) and review.tool_calls:
        # print("-> Going to internet_search")
        return "internet_search"

    if (
        isinstance(review, AIMessage)
        and "does not need any changes" in review.content.lower()
    ):
        # print("-> END")
        return END

    # print("-> Going to write_article")
    return "write_article"


#nodes
agent_builder=StateGraph(State)
agent_builder.add_node("write_article",write_article_node)
agent_builder.add_node("review_article",review_article_node)
agent_builder.add_node("internet_search",internet_search_node)

#edge
agent_builder.add_edge(START,"write_article")
agent_builder.add_edge("write_article","review_article")
agent_builder.add_edge("internet_search", "write_article")
agent_builder.add_conditional_edges("review_article",decide_internet_search,
                                    ["internet_search","write_article",END]
                                    )

agent=agent_builder.compile()

# while True:
#     query=input("Enter title:\n")
#     response=agent.invoke({
#         "topic":query,
#         "article":"",
#         "review":"",
#         "search_result":""
#     })
#     print(response["article"])
#     print()
#     print(response["review"].content)


def generate_article(topic: str):

    response = agent.invoke(
        {
            "topic": topic,
            "article": "",
            "review": "",
            "search_result": "",
            "workflow": []
        }
    )

    return {
        "article": response["article"],
        "review": response["review"].content,
        "workflow": response["workflow"]
    }

def generate_article_stream(topic: str):
    # print("Streaming started")
    initial_state = {
        "topic": topic,
        "article": "",
        "review": "",
        "search_result": "",
        "workflow": []
    }

    for event in agent.stream(initial_state):
        # print(event)
        yield event